#!/bin/sh

###################################################################
# Script to manually curate licenses in BOM-Base using the REST API.
# Optional $1 parameter specifies BOM-Base server (defaults to local).
###################################################################

set -e

BOM_BASE_URL="http://localhost:8080"
if [ "$1" ]; then
    BOM_BASE_URL=$1
fi

# Aborts if BOM-Base server cannot be reached
if [ $(curl --write-out '%{http_code}' --head --silent --output /dev/null $BOM_BASE_URL/packages) -ne 200 ]; then
    echo "Could not reach BOM-Base at URL $BOM_BASE_URL (see https://github.com/philips-software/bom-base)"
    exit 1
fi

###################################################################
# Curates a license URL
# $1 holds the license URL
# $2 holds the license for the URL
###################################################################
function curateURL() {
    curl --request POST -sS -H 'Content-Type: application/json' \
    -d "{\"license\":\"$1\",\"curation\":\"$2\"}" \
    "$BOM_BASE_URL/licenses" > /dev/null
}

###################################################################
# Append all curations here:
# (Don't forget to use the proper quotes)
###################################################################
curateURL 'http://developer.apple.com/library/mac/#samplecode/AppleJavaExtensions/Listings/README_txt.html#//apple_ref/doc/uid/DTS10000677-README_txt-DontLinkElementID_3' 'AppleJavaExtensions-proprietary'
curateURL 'http://www-128.ibm.com/developerworks/library/os-cpl.html' 'CPL-1.0'
curateURL 'http://www-128.ibm.com/developerworks/library/os-cpl.html0' 'CPL-1.0'
curateURL 'http://www-128.ibm.com/developerworks/library/os-cpl.html1' 'CPL-1.0'
curateURL 'http://www.gnu.org/copyleft/gpl.html' 'GPL-2.0-or-later'
curateURL 'http://www.gnu.org/licenses/gpl.txt' 'GPL-3.0-or-later'
curateURL 'https://www.eclipse.org/legal/epl-2.0/' 'EPL-2.0'
curateURL 'http://www.eclipse.org/org/documents/epl-v10.php' 'EPL-1.0'
curateURL 'https://www.eclipse.org/legal/epl-2.0' 'EPL-2.0'
curateURL 'http://www.apache.org/license/LICENSE-2.0.txt' 'Apache-2.0'
curateURL 'https://spdx.org/licenses/Apache-2.0' 'Apache-2.0'
curateURL 'https://www.apache.org/licenses/LICENSE-2.0.txt' 'Apache-2.0'
curateURL 'https://licenses.nuget.org/MS-PL%2520OR%2520Apache-2.0' 'MS-PL OR Apache-2.0'
curateURL 'https://licenses.nuget.org/MS-PL%20OR%20Apache-2.0' 'MS-PL OR Apache-2.0'
curateURL 'http://www.apache.org/licenses/LICENSE-2.0' 'Apache-2.0'
curateURL 'https://www.apache.org/licenses/LICENSE-2.0' 'Apache-2.0'
curateURL 'http://www.apache.org/licenses' 'Apache-2.0'
curateURL 'http://www.apache.org/licenses/' 'Apache-2.0'
curateURL 'https://spdx.org/licenses/Apache-2.0' 'Apache-2.0'
curateURL 'https://aws.amazon.com/apache2.0' 'Apache-2.0'
curateURL 'http://www.bouncycastle.org/licence.html' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html0' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html1' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html2' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html3' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html4' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html5' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html6' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html7' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html8' 'MIT'
curateURL 'http://www.bouncycastle.org/licence.html9' 'MIT'
curateURL 'http://creativecommons.org/publicdomain/zero/1.0/' 'CC0-1.0'
curateURL 'http://creativecommons.org/publicdomain/zero/1.0/0' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/0' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/1' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/2' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/3' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/4' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/5' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/6' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/7' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/8' 'CC0-1.0'
curateURL 'https://creativecommons.org/publicdomain/zero/1.0/9' 'CC0-1.0'
curateURL 'http://www.gnu.org/licenses/gpl-2.0.txt' 'GPL-2.0-only'
curateURL 'https://www.gnu.org/licenses/gpl-2.0.txt' 'GPL-2.0-only'
curateURL 'http://www.gnu.org/licenses/lgpl-2.1.html' 'LGPL-2.1-only'
curateURL 'https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html' 'LGPL-2.1-only'
curateURL 'http://www.gnu.org/licenses/lgpl.html' 'LGPL-3.0-or-later'
curateURL 'http://glassfish.java.net/public/CDDL+GPL_1_1.html' 'CDDL-1.1 OR GPL-2.0-only'
curateURL 'https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html' 'CDDL-1.1 OR GPL-2.0-only'
curateURL 'https://glassfish.dev.java.net/nonav/public/CDDL+GPL.html' 'CDDL-1.1 OR GPL-2.0-only'
curateURL ' https://glassfish.dev.java.net/public/CDDLv1.0.html' 'CDDL-1.0'
curateURL 'http://www.mozilla.org/MPL/MPL-1.0.txt' 'MPL-1.0'
curateURL 'https://www.mozilla.org/MPL/MPL-1.1.txt' 'MPL-1.1'
curateURL 'http://www.mozilla.org/MPL/2.0/' 'MPL-2.0'
curateURL 'http://www.wtfpl.net/' 'WTFPL'
curateURL 'https://spdx.org/licenses/BSD 2-Clause#licenseText' 'BSD-2-Clause'
curateURL 'http://aws.amazon.com/apache2.0/' 'Apache-2.0'
curateURL 'http://go.microsoft.com/fwlink/?LinkID=262998' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?LinkId=329770' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?LinkId=3297700' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?LinkId=3297701' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?LinkId=3297702' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?LinkId=3297703' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?LinkId=3297704' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?LinkId=529443' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?linkid=833178' 'Microsoft .NET Library License'
curateURL 'http://www.microsoft.com/web/webpi/eula/aspnetcomponent_rtw_ENU.htm' 'Microsoft .NET Library License'
curateURL 'http://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm' 'Microsoft .NET Library License'
curateURL 'https://webpifeed.blob.core.windows.net/webpifeed/eula/net_library_eula_enu.htm' 'Microsoft .NET Library License'
curateURL 'http://go.microsoft.com/fwlink/?LinkID=214339' 'Microsoft ASP.NET Library License'
curateURL 'https://licenses.nuget.org/MIT' 'MIT'
curateURL 'https://github.com/dotnet/corefx/blob/master/LICENSE.TXT' 'MIT'
curateURL 'https://www.mozilla.org/en-US/MPL/MPL-1.1.txt' 'MPL-1.1'
curateURL 'https://spdx.org/licenses/BSD' 'BSD-3-Clause'
curateURL 'https://spdx.org/licenses/MIT' 'MIT'
curateURL 'http://www.sun.com/cddl/cddl.html' 'CDDL-1.0'
curateURL 'https://opensource.org/licenses/MPL-2.0' 'MPL-2.0'
curateURL 'https://aka.ms/deprecateLicenseUrl' ''
curateURL 'http://opensource.org/licenses/ms-pl.html' 'MS-PL'
curateURL 'http://www.opensource.org/licenses/ms-pl' 'MS-PL'
curateURL 'http://opensource.org/licenses/MIT' 'MIT'
curateURL 'https://opensource.org/licenses/mit-license.php' 'MIT'
curateURL 'http://www.opensource.org/licenses/mit-license.php' 'MIT'
curateURL 'http://mpdreamz.mit-license.org/' 'MIT'
curateURL 'http://www.fsf.org/licensing/licenses/agpl-3.0.html' 'AGPL-3.0'
curateURL 'http://www.mozilla.org/MPL/MPL-1.1.txt' 'MPL-1.1'
curateURL 'https://www.gnu.org/software/classpath/license.html' 'GPL-2.0-or-later WITH Classpath-exception-2.0'
curateURL 'http://repository.jboss.org/licenses/gpl-2.0-ce.txt' 'GPL-2.0-or-later WITH Classpath-exception-2.0'
curateURL 'http://www.gnu.org/licenses/gpl-3.0-standalone.html' 'GPL-3.0-only'
curateURL 'https://opensource.org/licenses/MIT' 'MIT'
curateURL 'http://www.eclipse.org/legal/epl-2.0' 'EPL-2.0'
curateURL 'http://opensource.org/licenses/mit-license.php' 'MIT'
curateURL 'http://www.gnu.org/licenses/licenses.html' ''
curateURL 'http://opensource.org/licenses/BSD-3-Clause' 'BSD-3-Clause'
curateURL 'http://www.apache.org/licenses/LICENSE-2.0.txt' 'Apache-2.0'
curateURL 'http://www.apache.org/licenses/LICENSE-2.0.html' 'Apache-2.0'
curateURL 'http://www.gnu.org/licenses/gpl.html' 'GPL-3.0-or-later'
curateURL 'https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/LICENSE.txt' 'MIT'
curateURL 'http://www.eclipse.org/org/documents/edl-v10.php' 'BSD-3-Clause'
curateURL 'https://licenses.nuget.org/BSD-3-Clause' 'BSD-3-Clause'
curateURL 'https://www.gnu.org/licenses/lgpl-2.0.html' 'LGPL-2.0i-only'
curateURL 'pkg:maven/com.rabbitmq/http-client@1.0.0.M1' 'Apache-2.0'
curateURL 'pkg:maven/com.sendgrid/sendgrid-java@4.6.2' 'MIT'
curateURL 'pkg:maven/com.vlkan.log4j2/log4j2-logstash-layout@0.10' 'GPL-3.0-or-later'
curateURL 'pkg:maven/io.springfox.ui/springfox-swagger-ui-rfc6570@1.0.0' 'Apache-2.0'
curateURL 'pkg:maven/io.takari/maven-wrapper@0.1.2' 'EPL-1.0'
curateURL 'pkg:maven/junit/junit@4.11' 'CPL-1.0'
curateURL 'pkg:maven/org.assertj/assertj-core@2.6.0' 'Apache-2.0'
curateURL 'pkg:maven/org.dom4j/dom4j@2.1.0' 'DOM4J'
curateURL 'pkg:maven/org.dom4j/dom4j@2.1.3' 'DOM4J'
curateURL 'pkg:maven/org.gradle/gradle-base-annotations@6.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-base-services@4.0-milestone-1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-base-services@5.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-base-services@6.1-milestone-3' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-bootstrap@5.6.2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-build-cache-base@6.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-build-cache-packaging@6.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-build-cache@6.1-milestone-3' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-cli@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-core-api@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-core@3.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-core@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-execution@6.1-rc-3' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-files@6.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-hashing@6.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-ide-native@6.0.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-ide-play@6.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-ide@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-installation-beacon@5.6.4' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-ivy@5.6.2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-javascript@5.6.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-jvm-services@6.0.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-kotlin-dsl-tooling-models@6.1-milestone-3' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-language-java@6.1-milestone-1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-language-java@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-language-native@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-language-scala@6.0.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-launcher@6.1-rc-1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-logging@3.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-logging@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-maven@5.6.2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-messaging@3.5' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-messaging@6.0.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-model-core@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-model-groovy@6.1-milestone-2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-native@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-normalization-java@6.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-platform-base@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-platform-jvm@5.6.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-platform-native@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-platform-play@6.0.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-plugin-use@6.1-rc-1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-plugins@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-publish@5.6.2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-reporting@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-resources-gcs@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-resources-http@6.0-rc-2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-resources-s3@6.1-rc-2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-resources-sftp@6.0.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-resources@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-runtime-api-info@6.1-milestone-2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-scala@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-signing@5.6.2' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-snapshots@6.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-test-kit@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-testing-base@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-testing-junit-platform@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-testing-jvm@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-testing-native@6.0.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-tooling-api-builders@6.1.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-tooling-api@3.5.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-tooling-native@6.0.1' 'Apache-2.0'
curateURL 'pkg:maven/org.gradle/gradle-version-control@6.1-milestone-2' 'Apache-2.0'
curateURL 'pkg:maven/org.jacoco/jacoco@0.8.5' 'EPL-2.0'
curateURL 'pkg:maven/org.mockito/mockito-all@1.10.19' 'MIT'
curateURL 'pkg:maven/org.mockito/mockito-core@2.28.2' 'MIT'
curateURL 'pkg:maven/org.mockito/mockito-core@3.1.0' 'MIT'
curateURL 'pkg:maven/org.projectlombok/lombok@1.16.14' 'MIT'
curateURL 'pkg:maven/org.projectlombok/lombok@1.16.16' 'MIT'
curateURL 'pkg:maven/org.projectlombok/lombok@1.18.10' 'MIT'
curateURL 'pkg:maven/org.projectlombok/lombok@1.18.12' 'MIT'
curateURL 'pkg:maven/org.projectlombok/lombok@1.18.16' 'MIT'
curateURL 'pkg:maven/org.testng/testng@6.9.10' 'Apache-2.0'
curateURL 'pkg:maven/org.webjars.bower/angular-chart.js@0.8.8' 'BSD-3-Clause'
curateURL 'pkg:maven/redis.clients/jedis@2.10.2' 'MIT'
curateURL 'pkg:maven/redis.clients/jedis@2.9.0' 'MIT'
curateURL 'pkg:maven/xalan/xalan@2.7.2' 'Apache-2.0'
