@startuml

skinparam actorStyle hollow

actor Curator
actor Operator
rectangle "Client\nApplication" as Client
collections "Metadata\nSources" as Sources

usecase System

Client -> System: Request\npackage
Curator -u-> System: Curate\nmetadata
Operator -u-> System: Maintain\nsystem
System -> Sources: Harvest\nattributes

@enduml
